---
name: terranetes-policy
author: info@appvia.io
description: |
  The terranetes policy action is used as part of the workflows component
  (https://terranetes.appvia.io/terranetes-controller/category/workflows/) and
  used to verify a terraform module against organizational policy.
inputs:
  policy_url:
    description: |
      URL for your organizational policy repository. This is the repository
      which contains the Checkov i.e. github.com/appvia/terranetes-policy@v0.1.0
    default: ""
    required: false
  policy_version:
    description: |
      The branch or tag we should checkout in the policy repository
    default: ""
    required: false
  policy_ssh_key:
    description: |
      A deployment key used to clone the external policy repository. Review
      https://docs.github.com/en/developers/overview/managing-deploy-keys
    default: ""
    required: false
  configuration:
    description: |
      The path of the configuration file for checkov to use
    required: false
    default: ""
  directory:
    description: Is the directory containing the terranetes code
    required: true
    default: "."
  resource:
    description: Is the path of a terranetes Configuration resource to verify
    required: false
    default: ""
branding:
  color: purple
  icon: shield
runs:
  using: composite
  steps:
    - name: Security Policies
      if: ${{ inputs.policy_url != '' }}
      uses: actions/checkout@v3
      with:
        path: terranetes-policies
        ref: ${{ inputs.policy_version }}
        repository: ${{ inputs.policy_url }}
        ssh-key: ${{ inputs.policy_ssh_key }}
    - name: Validate Input
      shell: bash
      run: |
        if [[ -z "${{ inputs.resource }}" && -z "${{ inputs.directory }}" ]]; then
          echo "Either directory or resource must be defined"
          exit 1
        fi
    - name: Setup Environment
      id: config
      run: |
        if [[ -n "${{ inputs.policy_url }}" ]]; then
          echo "Enabling Central Security Policies"
          if [[ -n "${{ inputs.configuration }}" ]]; then
            if [[ -f "terranetes-policies/${{ inputs.configuration }}" ]]; then
              echo '::set-output name=config_file::terranetes-policies/${{ inputs.configuration }}'
            else
              echo "Checkov Configuration does not exist" && exit 1
            fi
          else
            if [[ -f "terranetes-policies/.checkov.yaml" ]]; then
              echo '::set-output name=config_file::terranetes-policies/.checkov.yaml'
            else
              echo '::set-output name=config_file::'
            fi
          fi
        else
          echo "No central security policies"
          echo '::set-output name=config_file::${{ inputs.configuration }}'
        fi
      shell: bash
    - name: Download CLI
      if: ${{ inputs.resource != '' }}
      run: |
        curl -sL https://github.com/appvia/terranetes-controller/releases/download/v0.3.6/tnctl-linux-amd64 -o /tmp/tnctl
        chmod +x /tmp/tnctl
        sudo cp /tmp/tnctl /bin/tnctl
      shell: bash
    - name: Generate Code
      if: ${{ inputs.resource != '' }}
      run: |
        tnctl convert configuration ${{ inputs.resource }} > ${{ inputs.directory }}/main.tf
      shell: bash
    - name: Verify Policy
      id: security
      uses: bridgecrewio/checkov-action@master
      with:
        config_file: "${{ steps.config.outputs.config_file }}"
        directory: "${{ inputs.directory }}"
        download_external_modules: true
        framework: "terraform"
